# Generated by Django 5.2.16 on 2026-07-16 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('job_type', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('process_name', models.CharField(help_text="Executable name to watch for, e.g. 'hashav.exe'", max_length=200)),
                ('title_pattern_type', models.CharField(choices=[('delimiter', 'Delimiter'), ('regex', 'Regex')], default='delimiter', max_length=20)),
                ('title_delimiter', models.CharField(blank=True, help_text="e.g. ' - ' to split 'ClientName - System' window titles", max_length=50)),
                ('title_delimiter_index', models.PositiveIntegerField(default=0, help_text='Which segment after splitting on the delimiter holds the client name')),
                ('title_regex', models.CharField(blank=True, help_text="Regex with a named group 'client', e.g. r'^(?P<client>.+?) - Hashav$'", max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('cancelled', 'Cancelled')], default='running', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='core.trackedsystem')),
            ],
            options={
                'verbose_name_plural': 'Time entries',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amount_owed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_billings', to='core.client')),
            ],
            options={
                'verbose_name_plural': 'Monthly billings',
                'ordering': ['-year', '-month'],
                'unique_together': {('client', 'year', 'month')},
            },
        ),
    ]
