# Generated by Django 5.2.16 on 2026-07-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedsystem',
            name='name',
            field=models.CharField(help_text="What to look for in open window titles, e.g. 'Google Translate' or 'Netflix'", max_length=200),
        ),
        migrations.AlterField(
            model_name='trackedsystem',
            name='process_name',
            field=models.CharField(blank=True, help_text="Optional: restrict detection to a specific executable, e.g. 'hashav.exe'. Leave blank to match this system's name in any open window's title, whether it's a browser tab or a standalone app.", max_length=200),
        ),
    ]
