# Generated by Django 4.2.4 on 2026-07-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trackedsystem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank_details',
            field=models.CharField(blank=True, max_length=100, verbose_name='פרטי בנק'),
        ),
        migrations.AddField(
            model_name='client',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='מספר תיק'),
        ),
        migrations.AddField(
            model_name='client',
            name='representation_start',
            field=models.CharField(blank=True, max_length=20, verbose_name='תחילת ייצוג'),
        ),
        migrations.AddField(
            model_name='client',
            name='representative',
            field=models.CharField(blank=True, max_length=100, verbose_name='מייצג'),
        ),
        migrations.AddField(
            model_name='client',
            name='sub_case',
            field=models.CharField(blank=True, max_length=50, verbose_name='ס.תיק'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='נושא מס'),
        ),
        migrations.AddField(
            model_name='client',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='חוליה'),
        ),
        migrations.AddField(
            model_name='client',
            name='validity_91',
            field=models.CharField(blank=True, max_length=50, verbose_name='תוקף 91'),
        ),
    ]
