# Generated by Django 5.2.16 on 2026-07-20 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_bank_details_client_case_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='מספר קבלה')),
                ('category', models.CharField(choices=[('food', 'מזון'), ('office_supplies', 'ציוד משרדי'), ('travel', 'נסיעות'), ('business', 'עבור העסק'), ('other', 'אחר')], default='other', max_length=20, verbose_name='קטגוריה')),
                ('receipt_date', models.DateField(verbose_name='תאריך הקבלה')),
                ('image', models.ImageField(upload_to='receipts/%Y/%m/', verbose_name='תמונת הקבלה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Receipts',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
    ]
