# Generated by Django 5.2.16 on 2026-07-20 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptChatUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipt_chat/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('approved', 'אושר'), ('discarded', 'בוטל'), ('error', 'שגיאה')], default='pending', max_length=10)),
                ('extraction', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_chat_uploads', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_uploads', to='core.receipt')),
            ],
            options={
                'verbose_name_plural': 'Receipt chat uploads',
                'ordering': ['created_at'],
            },
        ),
    ]
