# Generated by Django 5.2.16 on 2026-07-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_receiptchatupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptchatupload',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.FileField(upload_to='receipts/%Y/%m/', verbose_name='תמונת הקבלה'),
        ),
        migrations.AlterField(
            model_name='receiptchatupload',
            name='image',
            field=models.FileField(upload_to='receipt_chat/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='receiptchatupload',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין'), ('approved', 'אושר'), ('discarded', 'בוטל'), ('error', 'שגיאה'), ('awaiting_page_choice', 'ממתין לבחירת עמודים')], default='pending', max_length=25),
        ),
    ]
