# Generated by Django 5.2.16 on 2026-07-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('sign_in', 'כניסה לשעון'), ('sign_out', 'יציאה משעון'), ('hours', 'שעות'), ('receipt', 'קבלה'), ('billing', 'חיוב'), ('login', 'התחברות'), ('logout', 'התנתקות')], max_length=20),
        ),
    ]
